services:
  - type: web
    name: boarddo
    runtime: node
    plan: free
    rootDir: boarddo-app
    buildCommand: npm install && npm run build
    startCommand: npm run server
    healthCheckPath: /api/health
