services:
  - type: web
    name: witeboard
    runtime: node
    plan: free
    rootDir: whiteboard-app
    buildCommand: npm install && npm run build
    startCommand: npm run server
    healthCheckPath: /api/health
